<script lang="ts">
  import { onDestroy } from "svelte";
  import { type ClientStateConfig } from "@sila/client";
  import { clientState } from "../state/clientState.svelte";
  import SpaceEntry from "./SpaceEntry.svelte";
  import SwinsContainer from "../swins/SwinsContainer.svelte";
  import ContextMenuHandler from "./ContextMenuHandler.svelte";
  import ThemeManager from "./themes/ThemeManager.svelte";
  import FileGalleryModal from "./files/FileGalleryModal.svelte";

  // ./lib/compiled-style.css should be generated by npx tailwindcss at some point in the
  // build process, so if you don't see this file, make sure
  // you've run "npm run dev" or "npm run build" in the repository's root.
  import "@sila/client/compiled-style.css";

  let { config }: { config: ClientStateConfig | null } = $props();

  $effect(() => {
    if (config) {
      clientState.init(config);
    }
  });

  onDestroy(() => {
    clientState.cleanup();
  });

  console.log(
    "👋 Hey, if you see any bugs - please report them to https://github.com/silaorg/sila/issues",
  );
  console.log(
    "Reach out to the author of the project with any questions - Dmitry at d@dkury.com",
  );
</script>

<ThemeManager />

{#if config}
  <!-- Where our spaces are rendered -->
  <SpaceEntry />

  <!-- Setup stacking windows (popover windows with navigation) we use for new conversations, settings, etc -->
  <SwinsContainer swins={clientState.layout.swins} />

  <!-- Handle native and custom context menus -->
  <ContextMenuHandler />

  <!-- File Gallery Modal -->
  <FileGalleryModal />
{:else}
  Loading...
{/if}
