<script>
  console.log(
    "👋 Hey, if you see any bugs - please report them to https://github.com/supaorg/supa/issues",
  );
  console.log(
    "Reach out to the author of the project with any questions - Dmitry at d@dkury.com",
  );

  import SpaceEntry from "./SpaceEntry.svelte";

  // ./lib/compiled-style.css should be generated by npx tailwindcss at some point in the
  // build process, so if you don't see this file, make sure
  // you've run "npm run dev" or "npm run build" in the repository's root.
  import "@supa/client/compiled-style.css";
</script>

<SpaceEntry />
