<script>
  import SpaceEntry from "./SpaceEntry.svelte";

  // ./lib/compiled-style.css should be generated by npx tailwindcss at some point in the
  // build process, so if you don't see this file, make sure
  // you've run "npm run dev" or "npm run build" in the repository's root.
  import "@supa/client/compiled-style.css";
</script>

<SpaceEntry />